// =============================================================
//  QR Attendance System — Google Apps Script Backend
//  File   : Code.gs
//  Sheets : "Users"  → [UserID, Name, Email, QR_Link]
//           "Logs"   → [UserID, Name, Timestamp, Status]
// =============================================================

// ─── CONFIGURATION ────────────────────────────────────────────
// Paste your Google Sheet ID here (the long string in the URL)
var SHEET_ID      = 'YOUR_GOOGLE_SHEET_ID';

// Drive folder ID where QR images will be saved
var DRIVE_FOLDER_ID = 'YOUR_DRIVE_FOLDER_ID';

// Secret salt for HMAC-SHA256 signature verification.
// Change this to any random string — keep it private.
var HMAC_SECRET   = 'your-secret-salt-change-me';

// Cooldown in milliseconds — prevent duplicate rapid scans
var COOLDOWN_MS   = 5000;

// Sheet tab names
var SHEET_USERS   = 'Users';
var SHEET_LOGS    = 'Logs';


// =============================================================
//  doGet — serves the scanner HTML frontend
// =============================================================
function doGet(e) {
  return HtmlService
    .createHtmlOutputFromFile('index')
    .setTitle('QR Attendance Scanner')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}


// =============================================================
//  logEntry — called by the frontend via google.script.run
//
//  @param  {string} rawPayload  Either:
//            - a plain UserID string  (e.g. "USR_001")
//            - a JSON string          (e.g. '{"id":"USR_001","sig":"..."}')
//  @return {object} result
//            { status: 'success', name, userId, action, time }
//            { status: 'error',   message }
//            { status: 'duplicate', message }
// =============================================================
function logEntry(rawPayload) {

  // ── 1. Parse payload ──────────────────────────────────────
  var userId, sig;
  try {
    var parsed = JSON.parse(rawPayload);
    userId = parsed.id  || parsed.userId || String(parsed);
    sig    = parsed.sig || null;
  } catch (_) {
    userId = String(rawPayload).trim();
    sig    = null;
  }

  if (!userId) {
    return { status: 'error', message: 'Empty QR code — no user ID found.' };
  }

  // ── 2. Verify HMAC signature (if present) ─────────────────
  //  QR codes generated by generateQRCodes() embed a signature.
  //  If the scanned QR has no sig (plain ID), we still allow it
  //  but you can enforce signature-only by uncommenting the block.
  if (sig !== null) {
    var expectedSig = computeHmac(userId);
    if (sig !== expectedSig) {
      return { status: 'error', message: 'Invalid QR code — signature mismatch.' };
    }
  }
  // ── Uncomment to REQUIRE signatures on every scan:
  // else {
  //   return { status: 'error', message: 'QR code is not signed — rejected.' };
  // }

  // ── 3. Acquire script-level lock (serialise Sheet writes) ──
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000); // wait up to 10 s; throws if timeout
  } catch (_) {
    return { status: 'error', message: 'Server busy — please scan again.' };
  }

  try {
    var ss         = SpreadsheetApp.openById(SHEET_ID);
    var usersSheet = ss.getSheetByName(SHEET_USERS);
    var logsSheet  = ss.getSheetByName(SHEET_LOGS);

    // ── 4. Validate user exists in Users sheet ────────────────
    var usersData = usersSheet.getDataRange().getValues(); // [UserID, Name, Email, QR_Link]
    var userRow   = null;
    for (var i = 1; i < usersData.length; i++) {          // skip header row
      if (String(usersData[i][0]).trim() === userId) {
        userRow = usersData[i];
        break;
      }
    }
    if (!userRow) {
      return { status: 'error', message: 'User "' + userId + '" not found in database.' };
    }
    var userName = userRow[1];

    // ── 5. Cooldown check — inside the lock ───────────────────
    //  Find this user's most recent log entry.
    var logsData      = logsSheet.getDataRange().getValues(); // [UserID, Name, Timestamp, Status]
    var lastTimestamp = null;
    var lastStatus    = null;
    for (var j = logsData.length - 1; j >= 1; j--) {        // newest first (scan from bottom)
      if (String(logsData[j][0]).trim() === userId) {
        lastTimestamp = logsData[j][2];
        lastStatus    = logsData[j][3];
        break;
      }
    }

    var now = new Date();
    if (lastTimestamp) {
      var lastTime = new Date(lastTimestamp);
      if ((now - lastTime) < COOLDOWN_MS) {
        return {
          status:  'duplicate',
          message: 'Already scanned ' + Math.round((now - lastTime) / 1000) + 's ago — please wait.'
        };
      }
    }

    // ── 6. Determine IN / OUT (toggle from last status) ───────
    var action = (!lastStatus || lastStatus === 'OUT') ? 'IN' : 'OUT';

    // ── 7. Write log row ──────────────────────────────────────
    var isoTime = now.toISOString();
    logsSheet.appendRow([userId, userName, isoTime, action]);

    return {
      status: 'success',
      userId: userId,
      name:   userName,
      action: action,
      time:   isoTime
    };

  } finally {
    // ALWAYS release the lock, even if an error is thrown
    lock.releaseLock();
  }
}


// =============================================================
//  generateQRCodes
//  Run once (or whenever new users are added) from the Apps
//  Script editor: Extensions → Apps Script → Run → generateQRCodes
//
//  For each user in the Users sheet:
//    1. Builds a signed JSON payload  {id, sig}
//    2. Fetches a QR image from api.qrserver.com (no auth needed)
//    3. Saves it to Google Drive
//    4. Writes the Drive share-link back into column D (QR_Link)
// =============================================================
function generateQRCodes() {
  var ss         = SpreadsheetApp.openById(SHEET_ID);
  var sheet      = ss.getSheetByName(SHEET_USERS);
  var folder     = DriveApp.getFolderById(DRIVE_FOLDER_ID);
  var data       = sheet.getDataRange().getValues(); // [UserID, Name, Email, QR_Link]

  for (var i = 1; i < data.length; i++) {           // skip header
    var userId   = String(data[i][0]).trim();
    var userName = String(data[i][1]).trim();

    if (!userId) continue;

    // Build signed payload
    var payload = JSON.stringify({ id: userId, sig: computeHmac(userId) });

    // QR API URL (200×200 PNG, high error correction)
    var qrUrl = 'https://api.qrserver.com/v1/create-qr-code/?'
      + 'data='   + encodeURIComponent(payload)
      + '&size=300x300'
      + '&ecc=H'
      + '&margin=10';

    // Fetch QR image blob
    var response = UrlFetchApp.fetch(qrUrl, { muteHttpExceptions: true });
    if (response.getResponseCode() !== 200) {
      Logger.log('QR fetch failed for ' + userId + ': HTTP ' + response.getResponseCode());
      continue;
    }
    var blob = response.getBlob().setName('QR_' + userId + '_' + userName + '.png');

    // Remove old QR file for this user if it already exists
    var existingFiles = folder.getFilesByName('QR_' + userId + '_' + userName + '.png');
    while (existingFiles.hasNext()) existingFiles.next().setTrashed(true);

    // Save to Drive
    var file = folder.createFile(blob);
    file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
    var driveLink = 'https://drive.google.com/file/d/' + file.getId() + '/view';

    // Write link back to sheet column D (index 3)
    sheet.getRange(i + 1, 4).setValue(driveLink);

    Logger.log('Generated QR for ' + userId + ' (' + userName + '): ' + driveLink);
  }

  SpreadsheetApp.flush();
  Logger.log('✅ QR generation complete.');
}


// =============================================================
//  setupSheets
//  Run ONCE to create the Users and Logs sheets with headers.
//  Safe to run again — skips sheets that already exist.
// =============================================================
function setupSheets() {
  var ss = SpreadsheetApp.openById(SHEET_ID);

  // Users sheet
  var users = ss.getSheetByName(SHEET_USERS);
  if (!users) {
    users = ss.insertSheet(SHEET_USERS);
    users.appendRow(['UserID', 'Name', 'Email', 'QR_Link']);
    users.setFrozenRows(1);
    // Style header
    users.getRange(1, 1, 1, 4)
      .setBackground('#01696f')
      .setFontColor('#ffffff')
      .setFontWeight('bold');
    // Column widths
    users.setColumnWidth(1, 120);
    users.setColumnWidth(2, 160);
    users.setColumnWidth(3, 200);
    users.setColumnWidth(4, 320);
    Logger.log('Created Users sheet.');
  }

  // Logs sheet
  var logs = ss.getSheetByName(SHEET_LOGS);
  if (!logs) {
    logs = ss.insertSheet(SHEET_LOGS);
    logs.appendRow(['UserID', 'Name', 'Timestamp', 'Status']);
    logs.setFrozenRows(1);
    logs.getRange(1, 1, 1, 4)
      .setBackground('#01696f')
      .setFontColor('#ffffff')
      .setFontWeight('bold');
    logs.setColumnWidth(1, 120);
    logs.setColumnWidth(2, 160);
    logs.setColumnWidth(3, 200);
    logs.setColumnWidth(4, 80);
    Logger.log('Created Logs sheet.');
  }

  Logger.log('✅ Sheet setup complete.');
}


// =============================================================
//  addTestUsers
//  Populates 5 sample users so you can test immediately.
//  Run from the editor after setupSheets().
// =============================================================
function addTestUsers() {
  var ss    = SpreadsheetApp.openById(SHEET_ID);
  var sheet = ss.getSheetByName(SHEET_USERS);
  var testUsers = [
    ['USR_001', 'Riya Sharma',   'riya@example.com',   ''],
    ['USR_002', 'Arjun Mehta',   'arjun@example.com',  ''],
    ['USR_003', 'Priya Kapoor',  'priya@example.com',  ''],
    ['USR_004', 'Vikram Nair',   'vikram@example.com', ''],
    ['USR_005', 'Sneha Joshi',   'sneha@example.com',  ''],
  ];
  sheet.getRange(2, 1, testUsers.length, 4).setValues(testUsers);
  Logger.log('✅ Test users added. Now run generateQRCodes().');
}


// =============================================================
//  computeHmac — internal utility
//  Returns a hex string: HMAC-SHA256(userId, HMAC_SECRET)
// =============================================================
function computeHmac(userId) {
  var rawBytes = Utilities.computeHmacSha256Signature(
    userId,
    HMAC_SECRET,
    Utilities.Charset.UTF_8
  );
  // Convert byte array to hex string
  return rawBytes.map(function(b) {
    return ('0' + (b & 0xff).toString(16)).slice(-2);
  }).join('');
}
